from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 930)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_1_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1_1.setGeometry(QtCore.QRect(50, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_1_1.setFont(font)
        self.label_1_1.setObjectName("label_1_1")
        self.yt_url_input_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.yt_url_input_1.setGeometry(QtCore.QRect(100, 50, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yt_url_input_1.setFont(font)
        self.yt_url_input_1.setObjectName("yt_url_input_1")
        self.option_1 = QtWidgets.QComboBox(self.centralwidget)
        self.option_1.setGeometry(QtCore.QRect(660, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.option_1.setFont(font)
        self.option_1.setObjectName("option_1")
        self.check_run_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_run_1.setGeometry(QtCore.QRect(30, 50, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check_run_1.setFont(font)
        self.check_run_1.setText("")
        self.check_run_1.setObjectName("check_run_1")
        self.label_1_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_1_2.setGeometry(QtCore.QRect(30, 90, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_1_2.setFont(font)
        self.label_1_2.setObjectName("label_1_2")
        self.fileName_input_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.fileName_input_1.setGeometry(QtCore.QRect(110, 90, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fileName_input_1.setFont(font)
        self.fileName_input_1.setObjectName("fileName_input_1")
        self.label_1_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_1_3.setGeometry(QtCore.QRect(250, 90, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_1_3.setFont(font)
        self.label_1_3.setText("")
        self.label_1_3.setObjectName("label_1_3")
        self.label_2_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2_2.setGeometry(QtCore.QRect(30, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2_2.setFont(font)
        self.label_2_2.setObjectName("label_2_2")
        self.label_2_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_2_3.setGeometry(QtCore.QRect(250, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2_3.setFont(font)
        self.label_2_3.setText("")
        self.label_2_3.setObjectName("label_2_3")
        self.option_2 = QtWidgets.QComboBox(self.centralwidget)
        self.option_2.setGeometry(QtCore.QRect(660, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.option_2.setFont(font)
        self.option_2.setObjectName("option_2")
        self.check_run_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_run_2.setGeometry(QtCore.QRect(30, 140, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check_run_2.setFont(font)
        self.check_run_2.setText("")
        self.check_run_2.setObjectName("check_run_2")
        self.fileName_input_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.fileName_input_2.setGeometry(QtCore.QRect(110, 180, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fileName_input_2.setFont(font)
        self.fileName_input_2.setObjectName("fileName_input_2")
        self.yt_url_input_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.yt_url_input_2.setGeometry(QtCore.QRect(100, 140, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yt_url_input_2.setFont(font)
        self.yt_url_input_2.setObjectName("yt_url_input_2")
        self.label_2_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_2_1.setGeometry(QtCore.QRect(50, 140, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2_1.setFont(font)
        self.label_2_1.setObjectName("label_2_1")
        self.label_3_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_3_1.setGeometry(QtCore.QRect(50, 230, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3_1.setFont(font)
        self.label_3_1.setObjectName("label_3_1")
        self.label_3_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_3_2.setGeometry(QtCore.QRect(30, 270, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3_2.setFont(font)
        self.label_3_2.setObjectName("label_3_2")
        self.check_run_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_run_3.setGeometry(QtCore.QRect(30, 230, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check_run_3.setFont(font)
        self.check_run_3.setText("")
        self.check_run_3.setObjectName("check_run_3")
        self.yt_url_input_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.yt_url_input_3.setGeometry(QtCore.QRect(100, 230, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yt_url_input_3.setFont(font)
        self.yt_url_input_3.setObjectName("yt_url_input_3")
        self.fileName_input_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.fileName_input_3.setGeometry(QtCore.QRect(110, 270, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fileName_input_3.setFont(font)
        self.fileName_input_3.setObjectName("fileName_input_3")
        self.label_3_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3_3.setGeometry(QtCore.QRect(250, 270, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3_3.setFont(font)
        self.label_3_3.setText("")
        self.label_3_3.setObjectName("label_3_3")
        self.option_3 = QtWidgets.QComboBox(self.centralwidget)
        self.option_3.setGeometry(QtCore.QRect(660, 230, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.option_3.setFont(font)
        self.option_3.setObjectName("option_3")
        self.label_4_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_4_1.setGeometry(QtCore.QRect(50, 320, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4_1.setFont(font)
        self.label_4_1.setObjectName("label_4_1")
        self.label_4_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_4_2.setGeometry(QtCore.QRect(30, 360, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4_2.setFont(font)
        self.label_4_2.setObjectName("label_4_2")
        self.check_run_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_run_4.setGeometry(QtCore.QRect(30, 320, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check_run_4.setFont(font)
        self.check_run_4.setText("")
        self.check_run_4.setObjectName("check_run_4")
        self.yt_url_input_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.yt_url_input_4.setGeometry(QtCore.QRect(100, 320, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yt_url_input_4.setFont(font)
        self.yt_url_input_4.setObjectName("yt_url_input_4")
        self.fileName_input_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.fileName_input_4.setGeometry(QtCore.QRect(110, 360, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fileName_input_4.setFont(font)
        self.fileName_input_4.setObjectName("fileName_input_4")
        self.label_4_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_4_3.setGeometry(QtCore.QRect(250, 360, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4_3.setFont(font)
        self.label_4_3.setText("")
        self.label_4_3.setObjectName("label_4_3")
        self.option_4 = QtWidgets.QComboBox(self.centralwidget)
        self.option_4.setGeometry(QtCore.QRect(660, 320, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.option_4.setFont(font)
        self.option_4.setObjectName("option_4")
        self.label_5_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_5_1.setGeometry(QtCore.QRect(50, 410, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5_1.setFont(font)
        self.label_5_1.setObjectName("label_5_1")
        self.label_5_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_5_2.setGeometry(QtCore.QRect(30, 450, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5_2.setFont(font)
        self.label_5_2.setObjectName("label_5_2")
        self.check_run_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_run_5.setGeometry(QtCore.QRect(30, 410, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check_run_5.setFont(font)
        self.check_run_5.setText("")
        self.check_run_5.setObjectName("check_run_5")
        self.yt_url_input_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.yt_url_input_5.setGeometry(QtCore.QRect(100, 410, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yt_url_input_5.setFont(font)
        self.yt_url_input_5.setObjectName("yt_url_input_5")
        self.fileName_input_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.fileName_input_5.setGeometry(QtCore.QRect(110, 450, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fileName_input_5.setFont(font)
        self.fileName_input_5.setObjectName("fileName_input_5")
        self.label_5_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_5_3.setGeometry(QtCore.QRect(250, 450, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5_3.setFont(font)
        self.label_5_3.setText("")
        self.label_5_3.setObjectName("label_5_3")
        self.option_5 = QtWidgets.QComboBox(self.centralwidget)
        self.option_5.setGeometry(QtCore.QRect(660, 410, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.option_5.setFont(font)
        self.option_5.setObjectName("option_5")
        self.label_6_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_6_1.setGeometry(QtCore.QRect(50, 500, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6_1.setFont(font)
        self.label_6_1.setObjectName("label_6_1")
        self.label_6_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_6_2.setGeometry(QtCore.QRect(30, 540, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6_2.setFont(font)
        self.label_6_2.setObjectName("label_6_2")
        self.check_run_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_run_6.setGeometry(QtCore.QRect(30, 500, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check_run_6.setFont(font)
        self.check_run_6.setText("")
        self.check_run_6.setObjectName("check_run_6")
        self.yt_url_input_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.yt_url_input_6.setGeometry(QtCore.QRect(100, 500, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yt_url_input_6.setFont(font)
        self.yt_url_input_6.setObjectName("yt_url_input_6")
        self.fileName_input_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.fileName_input_6.setGeometry(QtCore.QRect(110, 540, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fileName_input_6.setFont(font)
        self.fileName_input_6.setObjectName("fileName_input_6")
        self.label_6_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_6_3.setGeometry(QtCore.QRect(250, 540, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6_3.setFont(font)
        self.label_6_3.setText("")
        self.label_6_3.setObjectName("label_6_3")
        self.option_6 = QtWidgets.QComboBox(self.centralwidget)
        self.option_6.setGeometry(QtCore.QRect(660, 500, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.option_6.setFont(font)
        self.option_6.setObjectName("option_6")
        self.label_7_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_7_1.setGeometry(QtCore.QRect(50, 590, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7_1.setFont(font)
        self.label_7_1.setObjectName("label_7_1")
        self.label_7_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_7_2.setGeometry(QtCore.QRect(30, 630, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7_2.setFont(font)
        self.label_7_2.setObjectName("label_7_2")
        self.check_run_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_run_7.setGeometry(QtCore.QRect(30, 590, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check_run_7.setFont(font)
        self.check_run_7.setText("")
        self.check_run_7.setObjectName("check_run_7")
        self.yt_url_input_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.yt_url_input_7.setGeometry(QtCore.QRect(100, 590, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yt_url_input_7.setFont(font)
        self.yt_url_input_7.setObjectName("yt_url_input_7")
        self.fileName_input_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.fileName_input_7.setGeometry(QtCore.QRect(110, 630, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fileName_input_7.setFont(font)
        self.fileName_input_7.setObjectName("fileName_input_7")
        self.label_7_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_7_3.setGeometry(QtCore.QRect(250, 630, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7_3.setFont(font)
        self.label_7_3.setText("")
        self.label_7_3.setObjectName("label_7_3")
        self.option_7 = QtWidgets.QComboBox(self.centralwidget)
        self.option_7.setGeometry(QtCore.QRect(660, 590, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.option_7.setFont(font)
        self.option_7.setObjectName("option_7")
        self.label_8_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_8_1.setGeometry(QtCore.QRect(50, 680, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8_1.setFont(font)
        self.label_8_1.setObjectName("label_8_1")
        self.label_8_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_8_2.setGeometry(QtCore.QRect(30, 720, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8_2.setFont(font)
        self.label_8_2.setObjectName("label_8_2")
        self.check_run_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.check_run_8.setGeometry(QtCore.QRect(30, 680, 21, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.check_run_8.setFont(font)
        self.check_run_8.setText("")
        self.check_run_8.setObjectName("check_run_8")
        self.yt_url_input_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.yt_url_input_8.setGeometry(QtCore.QRect(100, 680, 551, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.yt_url_input_8.setFont(font)
        self.yt_url_input_8.setObjectName("yt_url_input_8")
        self.fileName_input_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.fileName_input_8.setGeometry(QtCore.QRect(110, 720, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fileName_input_8.setFont(font)
        self.fileName_input_8.setObjectName("fileName_input_8")
        self.label_8_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_8_3.setGeometry(QtCore.QRect(250, 720, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8_3.setFont(font)
        self.label_8_3.setText("")
        self.label_8_3.setObjectName("label_8_3")
        self.option_8 = QtWidgets.QComboBox(self.centralwidget)
        self.option_8.setGeometry(QtCore.QRect(660, 680, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.option_8.setFont(font)
        self.option_8.setObjectName("option_8")
        self.file_output = QtWidgets.QTextEdit(self.centralwidget)
        self.file_output.setGeometry(QtCore.QRect(140, 800, 511, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.file_output.setFont(font)
        self.file_output.setObjectName("file_output")
        self.checkButton = QtWidgets.QPushButton(self.centralwidget)
        self.checkButton.setGeometry(QtCore.QRect(670, 800, 101, 31))
        self.checkButton.setObjectName("checkButton")
        self.msg_label = QtWidgets.QLabel(self.centralwidget)
        self.msg_label.setGeometry(QtCore.QRect(250, 840, 480, 31))
        self.msg_label.setObjectName("msg_label")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(280, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.folder_Button = QtWidgets.QPushButton(self.centralwidget)
        self.folder_Button.setGeometry(QtCore.QRect(30, 800, 101, 31))
        self.folder_Button.setObjectName("folder_Button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1_1.setText(_translate("MainWindow", "網址1:"))
        self.label_1_2.setText(_translate("MainWindow", "輸出檔名:"))
        self.label_2_2.setText(_translate("MainWindow", "輸出檔名:"))
        self.label_2_1.setText(_translate("MainWindow", "網址2:"))
        self.label_3_1.setText(_translate("MainWindow", "網址3:"))
        self.label_3_2.setText(_translate("MainWindow", "輸出檔名:"))
        self.label_4_1.setText(_translate("MainWindow", "網址4:"))
        self.label_4_2.setText(_translate("MainWindow", "輸出檔名:"))
        self.label_5_1.setText(_translate("MainWindow", "網址5:"))
        self.label_5_2.setText(_translate("MainWindow", "輸出檔名:"))
        self.label_6_1.setText(_translate("MainWindow", "網址6:"))
        self.label_6_2.setText(_translate("MainWindow", "輸出檔名:"))
        self.label_7_1.setText(_translate("MainWindow", "網址7:"))
        self.label_7_2.setText(_translate("MainWindow", "輸出檔名:"))
        self.label_8_1.setText(_translate("MainWindow", "網址8:"))
        self.label_8_2.setText(_translate("MainWindow", "輸出檔名:"))
        self.checkButton.setText(_translate("MainWindow", "Download"))
        self.title.setText(_translate("MainWindow", "YouTube Downloader"))
        self.folder_Button.setText(_translate("MainWindow", "輸出資料夾"))
        self.fileName_input_1.setText(_translate("MainWindow", "file1"))
        self.fileName_input_2.setText(_translate("MainWindow", "file2"))
        self.fileName_input_3.setText(_translate("MainWindow", "file3"))
        self.fileName_input_4.setText(_translate("MainWindow", "file4"))
        self.fileName_input_5.setText(_translate("MainWindow", "file5"))
        self.fileName_input_6.setText(_translate("MainWindow", "file6"))
        self.fileName_input_7.setText(_translate("MainWindow", "file7"))
        self.fileName_input_8.setText(_translate("MainWindow", "file8"))
        self.file_output.setText(_translate("MainWindow", "D:/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
